[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/manual"
to = "/downloads/manual.pdf"
status = 302

[[redirects]]
from = "/registro"
to = "/downloads/registro.pdf"
status = 302

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
